# Generated by Django 5.2.8 on 2025-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(default='def'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='def'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.TextField(default='def'),
        ),
    ]
