# Generated by Django 5.2.8 on 2025-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_telegram_confirmed_user_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
