# Generated by Django 5.2.8 on 2025-11-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notified',
        ),
    ]
