# Generated by Django 5.2.8 on 2025-11-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
