# Generated by Django 5.2.8 on 2025-11-24 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=8)),
                ('description', models.TextField()),
                ('topic', models.CharField(choices=[('programming', 'Programming'), ('algorithms', 'Algorithms'), ('math', 'Math'), ('language', 'Language')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
