# Generated by Django 5.2.8 on 2025-11-16 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meals', models.JSONField(default=dict)),
                ('water', models.PositiveIntegerField(default=0)),
                ('movement_minutes', models.PositiveIntegerField(default=0)),
                ('went_outside', models.BooleanField(default=False)),
                ('coffee_cups', models.PositiveIntegerField(default=0)),
                ('sugar', models.PositiveIntegerField(default=0)),
                ('mood', models.TextField(default='Good')),
                ('relaxation_minutes', models.PositiveIntegerField(default=0)),
                ('completed_challenge', models.BooleanField(default=False)),
                ('social_connections', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
