# Generated by Django 5.2.8 on 2025-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybalance',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
