# Generated by Django 5.2.8 on 2025-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailybalance_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybalance',
            name='breakfast_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailybalance',
            name='dinner_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailybalance',
            name='lunch_notified',
            field=models.BooleanField(default=False),
        ),
    ]
